/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/daily-collector/wrangler.jsonc --include-runtime=false workers/daily-collector/worker-configuration.d.ts` (hash: efda18424d15fbd0fc7bd086656c5cf0)
interface __BaseEnv_Env {
	ARCHIVE: R2Bucket;
	REDDIT_USER_AGENT: "reddit-insights-daily-collector/1.0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REDDIT_USER_AGENT">> {}
}
